####################################################################
#
#    UdonLibrary
#
#    Copyright (c) 2022-2023 udonrobo
#
#    Licensed under the MIT License.
#
####################################################################
#
#    Arduino Lint
#
####################################################################

name: Arduino Lint

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # all jobs should run

      matrix:
        board:
          - fqbn: arduino:avr:nano
          - fqbn: teensy:avr:teensy40
          - fqbn: rp2040:rp2040:rpipico

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=${HOME}/.local/bin sh

      - name: Install Board
        run: |
          arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          arduino-cli core update-index --additional-urls https://www.pjrc.com/teensy/td_156/package_teensy_index.json

      - name: Clone Other Libraries
        run: |
          arduino-cli lib install --git-url https://github.com/udonrobo/UdonArduinoSTL.git
          arduino-cli lib install --git-url https://github.com/adafruit/Adafruit_BusIO.git
          arduino-cli lib install --git-url https://github.com/adafruit/Adafruit_Sensor.git
          arduino-cli lib install --git-url https://github.com/adafruit/Adafruit_BNO055.git

      - name: Run Arduino Lint
        run: arduino-cli compile --library . -b ${{ matrix.board.fqbn }} --warnings all ./test/ArduinoLint/ArduinoLint.ino
