# https://github.com/arduino/compile-sketches#repository-1

name: Sketch Build

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    # 実行するOS
    runs-on: ubuntu-latest

    strategy:

      # すべてのジョブを実行する
      fail-fast: false

      matrix:

        # テストするボード
        board:

          - fqbn: arduino:avr:nano

          - fqbn: teensy:avr:teensy40
            platforms: |
              - name: teensy:avr
                source-url: https://www.pjrc.com/teensy/td_156/package_teensy_index.json

          - fqbn: rp2040:rp2040:rpipico
            platforms: |
              - name: rp2040:rp2040
                source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Arduino-cli test

        uses: arduino/compile-sketches@v1

        with:

          fqbn: ${{ matrix.board.fqbn }}

          platforms: ${{ matrix.board.platforms }}

          # テスト用スケッチがあるディレクトリ(再帰的)
          sketch-paths: |
            - ./test
            - ./example

          # 依存するライブラリ
          libraries: |
            - source-path: ./
            - source-url: https://github.com/autowp/arduino-mcp2515.git
            - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            - source-url: https://github.com/adafruit/Adafruit_Sensor.git
            - source-url: https://github.com/adafruit/Adafruit_BNO055.git
