name: Convert tabs to spaces
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert tabs to spaces
        uses: jeremycdn/tab-to-space@v1.0
        with:
          files: "src/**/*.{cpp,h,cc,hpp,cxx}"
          spaces: "4"
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m "Convert tabs to spaces" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          force: true
