name: CI

on:
  push:
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Submodules
        run: git submodule update --init

      - name: Build
        working-directory: ./test/GoogleTest
        run: |
          cmake -S . -B Build
          cmake --build Build

      - name: Run tests
        working-directory: ./test/GoogleTest/Build
        run: ctest
        